version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "8080:8080"
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      target: dev
    environment:
      DB_HOSTNAME: db
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DATABASE: zay
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: >
      sh -c "npm run db:reset && npm run dev"

  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: 'zay'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: